//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOK.DoorMonitor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>AL</string>
  <string>AK</string>
  <string>AZ</string>
  <string>AR</string>
  <string>CA</string>
  <string>CO</string>
  <string>CT</string>
  <string>DE</string>
  <string>FL</string>
  <string>GA</string>
  <string>HI</string>
  <string>ID</string>
  <string>IL</string>
  <string>IN</string>
  <string>IA</string>
  <string>KS</string>
  <string>KY</string>
  <string>LA</string>
  <string>ME</string>
  <string>MD</string>
  <string>MA</string>
  <string>MI</string>
  <string>MN</string>
  <string>MS</string>
  <string>MO</string>
  <string>MT</string>
  <string>NE</string>
  <string>NV</string>
  <string>NH</string>
  <string>NJ</string>
  <string>NM</string>
  <string>NY</string>
  <string>NC</string>
  <string>ND</string>
  <string>OH</string>
  <string>OK</string>
  <string>OR</string>
  <string>PA</string>
  <string>RI</string>
  <string>SC</string>
  <string>SD</string>
  <string>TN</string>
  <string>TX</string>
  <string>UT</string>
  <string>VT</string>
  <string>VA</string>
  <string>WA</string>
  <string>WV</string>
  <string>WI</string>
  <string>WY</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection StateNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["StateNames"]));
            }
            set {
                this["StateNames"] = value;
            }
        }
    }
}
