//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOK.MissionControl.StylesManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HOK.MissionControl.StylesManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 56603be6-aeb2-45d0-9ebc-2830fad6368b.
        /// </summary>
        internal static string HealthReportTrackerGuid {
            get {
                return ResourceManager.GetString("HealthReportTrackerGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StylesManager_Command.
        /// </summary>
        internal static string StylesManager_AdditionalButtonNames {
            get {
                return ResourceManager.GetString("StylesManager_AdditionalButtonNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles
        ///Manager.
        /// </summary>
        internal static string StylesManager_ButtonText {
            get {
                return ResourceManager.GetString("StylesManager_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool that allows you to manage Line, Text and Dimension Styles..
        /// </summary>
        internal static string StylesManager_Description {
            get {
                return ResourceManager.GetString("StylesManager_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stylesManager_32x32.png.
        /// </summary>
        internal static string StylesManager_ImageName {
            get {
                return ResourceManager.GetString("StylesManager_ImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles Manager.
        /// </summary>
        internal static string StylesManager_Name {
            get {
                return ResourceManager.GetString("StylesManager_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOK.MissionControl.StylesManager.
        /// </summary>
        internal static string StylesManager_Namespace {
            get {
                return ResourceManager.GetString("StylesManager_Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Control.
        /// </summary>
        internal static string StylesManager_PanelName {
            get {
                return ResourceManager.GetString("StylesManager_PanelName", resourceCulture);
            }
        }
    }
}
