//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOK.MissionControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HOK.MissionControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f4621647-f928-422a-8afa-e08293305ec8.
        /// </summary>
        internal static string CommunicatorGuid {
            get {
                return ResourceManager.GetString("CommunicatorGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 56603be6-aeb2-45d0-9ebc-2830fad6368b.
        /// </summary>
        internal static string HealthReportTrackerGuid {
            get {
                return ResourceManager.GetString("HealthReportTrackerGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOK.MissionControl.addin.
        /// </summary>
        internal static string MissionControl_AddinName {
            get {
                return ResourceManager.GetString("MissionControl_AddinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communicator_Command;WebsiteLink_Command.
        /// </summary>
        internal static string MissionControl_AdditionalButtons {
            get {
                return ResourceManager.GetString("MissionControl_AdditionalButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plug-in allows Design Technology Group to collect valuable information about the model and its contents that are then reported back to the user via online dashboard..
        /// </summary>
        internal static string MissionControl_Desc {
            get {
                return ResourceManager.GetString("MissionControl_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missionControl_32x32.png.
        /// </summary>
        internal static string MissionControl_ImageName {
            get {
                return ResourceManager.GetString("MissionControl_ImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Control.
        /// </summary>
        internal static string MissionControl_Name {
            get {
                return ResourceManager.GetString("MissionControl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOK.MissionControl.
        /// </summary>
        internal static string MissionControl_Namespace {
            get {
                return ResourceManager.GetString("MissionControl_Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Control.
        /// </summary>
        internal static string MissionControl_PanelName {
            get {
                return ResourceManager.GetString("MissionControl_PanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32d44b45-7bf6-49f1-9b81-f41ae929cfcb.
        /// </summary>
        internal static string SharedParameterTrackerGuid {
            get {
                return ResourceManager.GetString("SharedParameterTrackerGuid", resourceCulture);
            }
        }
    }
}
