//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOK.SheetManager.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HOK.SheetManager.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS &quot;Discipline&quot; (
        ///	`Discipline_Id`	TEXT NOT NULL UNIQUE,
        ///	`Discipline_Name`	TEXT NOT NULL UNIQUE,
        ///	PRIMARY KEY(Discipline_Id)
        ///).
        /// </summary>
        internal static string Discipline {
            get {
                return ResourceManager.GetString("Discipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE  IF NOT EXISTS &quot;LinkedProjects&quot; (
        ///	`LinkedProject_Id`	TEXT NOT NULL UNIQUE,
        ///	`LinkedProject_Number`	TEXT,
        ///	`LinkedProject_Name`	TEXT,
        ///	`LinkedProject_FilePath`	TEXT,
        ///	`LinkedProject_LinkedDate`	NUMERIC,
        ///	`LinkedProject_LinkedBy`	TEXT,
        ///	PRIMARY KEY(LinkedProject_Id)
        ///).
        /// </summary>
        internal static string LinkedProjects {
            get {
                return ResourceManager.GetString("LinkedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS &quot;LinkedRevisions&quot; (
        ///	`LinkedRevision_Id`	TEXT NOT NULL UNIQUE,
        ///	`LinkedRevision_Sequence`	INTEGER,
        ///	`LinkedRevision_Number`	TEXT,
        ///	`LinkedRevision_NumberType`	TEXT,
        ///	`LinkedRevision_Revision_Id`	TEXT,
        ///	`LinkedRevision_Project_Id`	TEXT,
        ///	`LinkedRevision_Element_Id`	TEXT,
        ///	`LinkedRevision_IsSource`	INTEGER,
        ///	PRIMARY KEY(LinkedRevision_Id)
        ///).
        /// </summary>
        internal static string LinkedRevisions {
            get {
                return ResourceManager.GetString("LinkedRevisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS &quot;LinkedSheets&quot; (
        ///	`LinkedSheet_Id`	TEXT NOT NULL UNIQUE,
        ///	`LinkedSheet_Sheet_Id`	TEXT,
        ///	`LinkedSheet_Project_Id`	TEXT,
        ///	`LinkedSheet_Element_Id`	TEXT,
        ///	`LinkedSheet_IsSource`	INTEGER,
        ///	PRIMARY KEY(LinkedSheet_Id)
        ///).
        /// </summary>
        internal static string LinkedSheets {
            get {
                return ResourceManager.GetString("LinkedSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS &quot;ReplaceItems&quot; (
        ///	`ReplaceItem_Id`	TEXT NOT NULL UNIQUE,
        ///	`ReplaceItem_Type`	TEXT NOT NULL,
        ///	`ReplaceItem_Parameter`	TEXT NOT NULL,
        ///	`ReplaceItem_Source_Id`	TEXT,
        ///	`ReplaceItem_Source_Value`	TEXT,
        ///	`ReplaceItem_Target_Value`	TEXT,
        ///	PRIMARY KEY(ReplaceItem_Id)
        ///).
        /// </summary>
        internal static string ReplaceItems {
            get {
                return ResourceManager.GetString("ReplaceItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS &quot;RevisionDocuments&quot; (
        ///	`Document_Id`	TEXT NOT NULL UNIQUE,
        ///	`Document_Title`	TEXT,
        ///	`Document_Path`	TEXT,
        ///	`Document_Contents`	BLOB,
        ///	PRIMARY KEY(Document_Id)
        ///).
        /// </summary>
        internal static string RevisionDocuments {
            get {
                return ResourceManager.GetString("RevisionDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS &quot;Revisions&quot; (
        ///	`Revision_Id`	TEXT NOT NULL UNIQUE,
        ///	`Revision_Description`	TEXT,
        ///	`Revision_IssuedBy`	TEXT,
        ///	`Revision_IssuedTo`	TEXT,
        ///	`Revision_Date`	TEXT,
        ///	`Revision_Document_Id`	TEXT,
        ///	PRIMARY KEY(Revision_Id)
        ///).
        /// </summary>
        internal static string Revisions {
            get {
                return ResourceManager.GetString("Revisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE  IF NOT EXISTS  &quot;RevisionsOnSheet&quot; (
        ///	`RevisionsOnSheet_Id`	TEXT NOT NULL UNIQUE,
        ///	`RevisionsOnSheet_Sheet_Id`	TEXT,
        ///	`RevisionsOnSheet_Revision_Id`	TEXT,
        ///	`RevisionsOnSheet_Include`	INTEGER,
        ///	PRIMARY KEY(RevisionsOnSheet_Id)
        ///).
        /// </summary>
        internal static string RevisionsOnSheet {
            get {
                return ResourceManager.GetString("RevisionsOnSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS &quot;SheetParameters&quot; (
        ///	`Parameter_Id`	TEXT NOT NULL UNIQUE,
        ///	`Parameter_Name`	TEXT NOT NULL,
        ///	`Parameter_Type`	TEXT,
        ///	PRIMARY KEY(Parameter_Id)
        ///).
        /// </summary>
        internal static string SheetParameters {
            get {
                return ResourceManager.GetString("SheetParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS &quot;SheetParameterValues&quot; (
        ///	`ParameterValue_Id`	TEXT NOT NULL,
        ///	`ParameterValue_Sheet_Id`	TEXT NOT NULL,
        ///	`ParameterValue_Parameter_Id`	TEXT,
        ///	`ParameterValue_Parameter_Value`	TEXT,
        ///	PRIMARY KEY(ParameterValue_Id)
        ///).
        /// </summary>
        internal static string SheetParameterValues {
            get {
                return ResourceManager.GetString("SheetParameterValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS &quot;Sheets&quot; (
        ///	`Sheet_Id`	TEXT NOT NULL UNIQUE,
        ///	`Sheet_Number`	TEXT NOT NULL,
        ///	`Sheet_Name`	TEXT,
        ///	`Sheet_Discipline_Id`	TEXT,
        ///	PRIMARY KEY(Sheet_Id)
        ///).
        /// </summary>
        internal static string Sheets {
            get {
                return ResourceManager.GetString("Sheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS &quot;Views&quot; (
        ///	`View_Id`	TEXT NOT NULL UNIQUE,
        ///	`View_Name`	TEXT NOT NULL,
        ///	`View_Sheet_Id`	TEXT,
        ///	`View_ViewType_Id`	TEXT,
        ///	`View_LocationX`	REAL,
        ///	`View_LocationY`	REAL,
        ///	PRIMARY KEY(View_Id)
        ///).
        /// </summary>
        internal static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS &quot;ViewTypes&quot; (
        ///	`ViewType_Id`	TEXT NOT NULL UNIQUE,
        ///	`ViewType_Name`	TEXT NOT NULL,
        ///	`ViewType_Enum`	TEXT,
        ///		PRIMARY KEY(ViewType_Id)
        ///).
        /// </summary>
        internal static string ViewTypes {
            get {
                return ResourceManager.GetString("ViewTypes", resourceCulture);
            }
        }
    }
}
