// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>SolibriBatchSetup</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>False</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace SolibriBatchSetup
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class batch
    {

        private target targetField = new target();

        private string nameField = "Simple Batch";

        private string defaultField = "root";

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public target target
        {
            get
            {
                return this.targetField;
            }
            set
            {
                this.targetField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @default
        {
            get
            {
                return this.defaultField;
            }
            set
            {
                this.defaultField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class target
    {

        private List<model> openmodelField = new List<model>();

        private List<model> openrulesetField = new List<model>();

        private List<object> checkField = new List<object>();

        private List<autocomment> autocommentField = new List<autocomment>();

        private List<object> createpresentationField = new List<object>();

        private List<coordination> coordinationreportField = new List<coordination>();

        private List<pdf> generalreportField = new List<pdf>();

        private List<pdf> writereportField = new List<pdf>();

        private List<bcf> bcfreportField = new List<bcf>();

        private List<model> savemodelField = new List<model>();

        private List<object> closemodelField = new List<object>();

        private object exitField = new object();

        private string nameField = "root";

        public target()
        {
            
        }

        [System.Xml.Serialization.XmlElementAttribute("openmodel", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<model> openmodel
        {
            get
            {
                return this.openmodelField;
            }
            set
            {
                this.openmodelField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("openruleset", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<model> openruleset
        {
            get
            {
                return this.openrulesetField;
            }
            set
            {
                this.openrulesetField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("check", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<object> check
        {
            get
            {
                return this.checkField;
            }
            set
            {
                this.checkField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("autocomment", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<autocomment> autocomment
        {
            get
            {
                return this.autocommentField;
            }
            set
            {
                this.autocommentField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("createpresentation", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<object> createpresentation
        {
            get
            {
                return this.createpresentationField;
            }
            set
            {
                this.createpresentationField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("coordinationreport", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<coordination> coordinationreport
        {
            get
            {
                return this.coordinationreportField;
            }
            set
            {
                this.coordinationreportField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("generalreport", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<pdf> generalreport
        {
            get
            {
                return this.generalreportField;
            }
            set
            {
                this.generalreportField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("writereport", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<pdf> writereport
        {
            get
            {
                return this.writereportField;
            }
            set
            {
                this.writereportField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("bcfreport", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<bcf> bcfreport
        {
            get
            {
                return this.bcfreportField;
            }
            set
            {
                this.bcfreportField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("savemodel", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<model> savemodel
        {
            get
            {
                return this.savemodelField;
            }
            set
            {
                this.savemodelField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("closemodel", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<object> closemodel
        {
            get
            {
                return this.closemodelField;
            }
            set
            {
                this.closemodelField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object exit
        {
            get
            {
                return this.exitField;
            }
            set
            {
                this.exitField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class model
    {

        private string fileField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string file
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class coordination
    {

        private string fileField;

        private string templatefileField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string file
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string templatefile
        {
            get
            {
                return this.templatefileField;
            }
            set
            {
                this.templatefileField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class pdf
    {

        private string pdffileField;

        private string rtffileField;

        private bool majorField;

        private bool majorFieldSpecified;

        private bool normalField;

        private bool normalFieldSpecified;

        private bool minorField;

        private bool minorFieldSpecified;

        private bool rejectedField;

        private bool rejectedFieldSpecified;

        private bool acceptedField;

        private bool acceptedFieldSpecified;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pdffile
        {
            get
            {
                return this.pdffileField;
            }
            set
            {
                this.pdffileField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rtffile
        {
            get
            {
                return this.rtffileField;
            }
            set
            {
                this.rtffileField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool major
        {
            get
            {
                return this.majorField;
            }
            set
            {
                this.majorField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool majorSpecified
        {
            get
            {
                return this.majorFieldSpecified;
            }
            set
            {
                this.majorFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool normal
        {
            get
            {
                return this.normalField;
            }
            set
            {
                this.normalField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool normalSpecified
        {
            get
            {
                return this.normalFieldSpecified;
            }
            set
            {
                this.normalFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool minor
        {
            get
            {
                return this.minorField;
            }
            set
            {
                this.minorField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minorSpecified
        {
            get
            {
                return this.minorFieldSpecified;
            }
            set
            {
                this.minorFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool rejected
        {
            get
            {
                return this.rejectedField;
            }
            set
            {
                this.rejectedField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rejectedSpecified
        {
            get
            {
                return this.rejectedFieldSpecified;
            }
            set
            {
                this.rejectedFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool accepted
        {
            get
            {
                return this.acceptedField;
            }
            set
            {
                this.acceptedField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool acceptedSpecified
        {
            get
            {
                return this.acceptedFieldSpecified;
            }
            set
            {
                this.acceptedFieldSpecified = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class bcf
    {

        private string fileField;

        private string versionField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string file
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class autocomment
    {

        private string zoomField = "TRUE";

        private string maxsnapshotsincategoryField = "3";

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zoom
        {
            get
            {
                return this.zoomField;
            }
            set
            {
                this.zoomField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string maxsnapshotsincategory
        {
            get
            {
                return this.maxsnapshotsincategoryField;
            }
            set
            {
                this.maxsnapshotsincategoryField = value;
            }
        }
    }
}
