// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>BCFDBManager</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace BCFDBManager
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class VisualizationInfo
    {
        private List<Component> componentsField;

        private OrthogonalCamera orthogonalCameraField;

        private PerspectiveCamera perspectiveCameraField;

        private List<Line> linesField;

        private List<ClippingPlane> clippingPlanesField;

        private List<VisualizationInfoBitmaps> bitmapsField;

        public VisualizationInfo()
        {
            this.bitmapsField = new List<VisualizationInfoBitmaps>();
            this.clippingPlanesField = new List<ClippingPlane>();
            this.linesField = new List<Line>();
            this.perspectiveCameraField = new PerspectiveCamera();
            this.orthogonalCameraField = new OrthogonalCamera();
            this.componentsField = new List<Component>();
        }

        public VisualizationInfo(VisualizationInfo visInfo)
        {
            this.Components = visInfo.Components;
            this.OrthogonalCamera = visInfo.OrthogonalCamera;
            this.PerspectiveCamera = visInfo.PerspectiveCamera;
            this.Lines = visInfo.Lines;
            this.ClippingPlanes = visInfo.ClippingPlanes;
            this.Bitmaps = visInfo.Bitmaps;
        }

        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public List<Component> Components
        {
            get
            {
                return this.componentsField;
            }
            set
            {
                this.componentsField = value;
            }
        }

        public OrthogonalCamera OrthogonalCamera
        {
            get
            {
                return this.orthogonalCameraField;
            }
            set
            {
                this.orthogonalCameraField = value;
            }
        }

        public PerspectiveCamera PerspectiveCamera
        {
            get
            {
                return this.perspectiveCameraField;
            }
            set
            {
                this.perspectiveCameraField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public List<Line> Lines
        {
            get
            {
                return this.linesField;
            }
            set
            {
                this.linesField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public List<ClippingPlane> ClippingPlanes
        {
            get
            {
                return this.clippingPlanesField;
            }
            set
            {
                this.clippingPlanesField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Bitmaps")]
        public List<VisualizationInfoBitmaps> Bitmaps
        {
            get
            {
                return this.bitmapsField;
            }
            set
            {
                this.bitmapsField = value;
            }
        }

        public virtual VisualizationInfo Clone()
        {
            return ((VisualizationInfo)(this.MemberwiseClone()));
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class Component
    {
        private string guidField = "";

        private string originatingSystemField = "";

        private string authoringToolIdField = "";

        private string ifcGuidField = "";

        private bool selectedField;

        private bool selectedFieldSpecified;

        private bool visibleField;

        private byte[] colorField;

        public Component()
        {
            this.guidField = System.Guid.NewGuid().ToString();
            this.visibleField = true;
        }

        public Component(Component component)
        {
            this.Guid = component.Guid;
            this.OriginatingSystem = component.OriginatingSystem;
            this.AuthoringToolId = component.AuthoringToolId;
            this.IfcGuid = component.IfcGuid;
            this.Selected = component.Selected;
            this.SelectedSpecified = component.SelectedSpecified;
            this.Visible = component.Visible;
            this.Color = component.Color;
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public string Guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }

        public string OriginatingSystem
        {
            get
            {
                return this.originatingSystemField;
            }
            set
            {
                this.originatingSystemField = value;
            }
        }

        public string AuthoringToolId
        {
            get
            {
                return this.authoringToolIdField;
            }
            set
            {
                this.authoringToolIdField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
        public string IfcGuid
        {
            get
            {
                return this.ifcGuidField;
            }
            set
            {
                this.ifcGuidField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Selected
        {
            get
            {
                return this.selectedField;
            }
            set
            {
                this.selectedField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SelectedSpecified
        {
            get
            {
                return this.selectedFieldSpecified;
            }
            set
            {
                this.selectedFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Visible
        {
            get
            {
                return this.visibleField;
            }
            set
            {
                this.visibleField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "hexBinary")]
        public byte[] Color
        {
            get
            {
                return this.colorField;
            }
            set
            {
                this.colorField = value;
            }
        }

        public virtual Component Clone()
        {
            return ((Component)(this.MemberwiseClone()));
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class ClippingPlane
    {
        private string guidField = "";

        private Point locationField;

        private Direction directionField;

        public ClippingPlane()
        {
            this.guidField = System.Guid.NewGuid().ToString();
            this.directionField = new Direction();
            this.locationField = new Point();
        }

        public ClippingPlane(ClippingPlane clippingPlane)
        {
            this.Guid = clippingPlane.Guid;
            this.Location = clippingPlane.Location;
            this.Direction = clippingPlane.Direction;
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public string Guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }

        public Point Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        public Direction Direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }

        public virtual ClippingPlane Clone()
        {
            return ((ClippingPlane)(this.MemberwiseClone()));
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class Point
    {
        private string guidField = "";

        private double xField;

        private double yField;

        private double zField;

        public Point()
        {
            this.guidField = System.Guid.NewGuid().ToString();
        }

        public Point(Point point)
        {
            this.Guid = point.Guid;
            this.X = point.X;
            this.Y = point.Y;
            this.Z = point.Z;

        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public string Guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }

        public double X
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }

        public double Y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }

        public double Z
        {
            get
            {
                return this.zField;
            }
            set
            {
                this.zField = value;
            }
        }

        public virtual Point Clone()
        {
            return ((Point)(this.MemberwiseClone()));
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class Direction
    {
        private string guidField = "";

        private double xField;

        private double yField;

        private double zField;

        public Direction()
        {
            this.guidField = System.Guid.NewGuid().ToString();
        }

        public Direction(Direction direction)
        {
            this.Guid = direction.Guid;
            this.X = direction.X;
            this.Y = direction.Y;
            this.Z = direction.Z;
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public string Guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }

        public double X
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }

        public double Y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }

        public double Z
        {
            get
            {
                return this.zField;
            }
            set
            {
                this.zField = value;
            }
        }

        public virtual Direction Clone()
        {
            return ((Direction)(this.MemberwiseClone()));
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class Line
    {
        private string guidField = "";

        private Point startPointField;

        private Point endPointField;

        public Line()
        {
            this.guidField = System.Guid.NewGuid().ToString();
            this.endPointField = new Point();
            this.startPointField = new Point();
        }

        public Line(Line line)
        {
            this.Guid = line.Guid;
            this.EndPoint = line.EndPoint;
            this.StartPoint = line.StartPoint;
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public string Guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }

        public Point StartPoint
        {
            get
            {
                return this.startPointField;
            }
            set
            {
                this.startPointField = value;
            }
        }

        public Point EndPoint
        {
            get
            {
                return this.endPointField;
            }
            set
            {
                this.endPointField = value;
            }
        }

        public virtual Line Clone()
        {
            return ((Line)(this.MemberwiseClone()));
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class PerspectiveCamera
    {
        private string guidField = "";

        private Point cameraViewPointField;

        private Direction cameraDirectionField;

        private Direction cameraUpVectorField;

        private double fieldOfViewField;

        public PerspectiveCamera()
        {
            this.guidField = System.Guid.NewGuid().ToString();
            this.cameraUpVectorField = new Direction();
            this.cameraDirectionField = new Direction();
            this.cameraViewPointField = new Point();
        }

        public PerspectiveCamera(PerspectiveCamera persCamera)
        {
            this.Guid = persCamera.Guid;
            this.CameraViewPoint = persCamera.CameraViewPoint;
            this.CameraDirection = persCamera.CameraDirection;
            this.CameraUpVector = persCamera.CameraUpVector;
            this.FieldOfView = persCamera.FieldOfView;
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public string Guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }

        public Point CameraViewPoint
        {
            get
            {
                return this.cameraViewPointField;
            }
            set
            {
                this.cameraViewPointField = value;
            }
        }

        public Direction CameraDirection
        {
            get
            {
                return this.cameraDirectionField;
            }
            set
            {
                this.cameraDirectionField = value;
            }
        }

        public Direction CameraUpVector
        {
            get
            {
                return this.cameraUpVectorField;
            }
            set
            {
                this.cameraUpVectorField = value;
            }
        }

        public double FieldOfView
        {
            get
            {
                return this.fieldOfViewField;
            }
            set
            {
                this.fieldOfViewField = value;
            }
        }

        public virtual PerspectiveCamera Clone()
        {
            return ((PerspectiveCamera)(this.MemberwiseClone()));
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class OrthogonalCamera
    {
        private string guidField = "";

        private Point cameraViewPointField;

        private Direction cameraDirectionField;

        private Direction cameraUpVectorField;

        private double viewToWorldScaleField;

        public OrthogonalCamera()
        {
            this.guidField = System.Guid.NewGuid().ToString();
            this.cameraUpVectorField = new Direction();
            this.cameraDirectionField = new Direction();
            this.cameraViewPointField = new Point();
        }

        public OrthogonalCamera(OrthogonalCamera orthoCamera)
        {
            this.Guid = orthoCamera.Guid;
            this.CameraUpVector = orthoCamera.CameraUpVector;
            this.CameraDirection = orthoCamera.CameraDirection;
            this.CameraViewPoint = orthoCamera.CameraViewPoint;
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public string Guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }

        public Point CameraViewPoint
        {
            get
            {
                return this.cameraViewPointField;
            }
            set
            {
                this.cameraViewPointField = value;
            }
        }

        public Direction CameraDirection
        {
            get
            {
                return this.cameraDirectionField;
            }
            set
            {
                this.cameraDirectionField = value;
            }
        }

        public Direction CameraUpVector
        {
            get
            {
                return this.cameraUpVectorField;
            }
            set
            {
                this.cameraUpVectorField = value;
            }
        }

        public double ViewToWorldScale
        {
            get
            {
                return this.viewToWorldScaleField;
            }
            set
            {
                this.viewToWorldScaleField = value;
            }
        }

        public virtual OrthogonalCamera Clone()
        {
            return ((OrthogonalCamera)(this.MemberwiseClone()));
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class VisualizationInfoBitmaps
    {
        private string guidField = "";

        private BitmapFormat bitmapField;

        private string referenceField = "";

        private Point locationField;

        private Direction normalField;

        private Direction upField;

        private double heightField;

        private byte[] bitmapImageField;

        public VisualizationInfoBitmaps()
        {
            this.guidField = System.Guid.NewGuid().ToString();
            this.upField = new Direction();
            this.normalField = new Direction();
            this.locationField = new Point();
        }

        public VisualizationInfoBitmaps(VisualizationInfoBitmaps visInfoBitmaps)
        {
            this.Guid = visInfoBitmaps.Guid;
            this.Bitmap = visInfoBitmaps.Bitmap;
            this.Reference = visInfoBitmaps.Reference;
            this.Location = visInfoBitmaps.Location;
            this.Normal = visInfoBitmaps.Normal;
            this.Up = visInfoBitmaps.Up;
            this.Height = visInfoBitmaps.Height;
            this.BitmapImage = visInfoBitmaps.BitmapImage;
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public string Guid
        {
            get
            {
                return this.guidField;
            }
            set
            {
                this.guidField = value;
            }
        }

        public BitmapFormat Bitmap
        {
            get
            {
                return this.bitmapField;
            }
            set
            {
                this.bitmapField = value;
            }
        }

        public string Reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }

        public Point Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        public Direction Normal
        {
            get
            {
                return this.normalField;
            }
            set
            {
                this.normalField = value;
            }
        }

        public Direction Up
        {
            get
            {
                return this.upField;
            }
            set
            {
                this.upField = value;
            }
        }

        public double Height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public byte[] BitmapImage
        {
            get
            {
                return this.bitmapImageField;
            }
            set
            {
                this.bitmapImageField = value;
            }
        }

        public virtual VisualizationInfoBitmaps Clone()
        {
            return ((VisualizationInfoBitmaps)(this.MemberwiseClone()));
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public enum BitmapFormat
    {

        /// <remarks/>
        PNG,

        /// <remarks/>
        JPG,
    }
}
